# Generated by Django 5.2.8 on 2026-05-19 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('homepage_carousel', 'Homepage Carousel'), ('search_top', 'Top of Search Results'), ('featured_artisan', 'Featured Artisan'), ('category_banner', 'Category Banner')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('target_url', models.URLField(blank=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ads', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(limit_choices_to={'role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('order', 'Order Issue'), ('payment', 'Payment Issue'), ('product', 'Product Issue'), ('account', 'Account Issue'), ('vendor', 'Vendor Complaint'), ('other', 'Other')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
