/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-surface": "#1d1b16",
        "surface-container-low": "#f9f3e9",
        "inverse-primary": "#ffb3b3",
        "primary-fixed": "#ffdad9",
        "error-container": "#ffdad6",
        "tertiary-container": "#756f6b",
        "surface-dim": "#dfd9d0",
        "tertiary-fixed-dim": "#cdc5c0",
        "on-primary-fixed": "#400009",
        "background": "#fff9ef",
        "surface-variant": "#e7e2d8",
        "on-secondary-fixed": "#1b1c19",
        "on-primary-fixed-variant": "#920021",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface-bright": "#fff9ef",
        "on-secondary-container": "#656461",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c8c6c2",
        "tertiary": "#5c5753",
        "primary-container": "#de0d3a",
        "secondary-fixed": "#e4e2de",
        "surface-container-highest": "#e7e2d8",
        "on-tertiary-fixed-variant": "#4b4642",
        "primary-fixed-dim": "#ffb3b3",
        "on-tertiary-fixed": "#1e1b18",
        "surface-container-high": "#ede7de",
        "surface-tint": "#bf002f",
        "inverse-surface": "#32302a",
        "inverse-on-surface": "#f6f0e6",
        "surface": "#fff9ef",
        "on-surface-variant": "#5d3f3f",
        "secondary": "#5f5e5b",
        "tertiary-fixed": "#e9e1dc",
        "on-background": "#1d1b16",
        "surface-container": "#f3ede3",
        "on-tertiary-container": "#fdf4ef",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#474744",
        "on-primary-container": "#fff2f1",
        "outline": "#916e6e",
        "primary": "#b2002b",
        "secondary-container": "#e4e2de",
        "outline-variant": "#e6bdbc"
      },
      fontFamily: {
        headline: ["Playfair Display", "serif"],
        display: ["Playfair Display", "serif"],
        body: ["DM Sans", "sans-serif"],
        label: ["DM Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
