export const SELECTORS = {
  login: {
    username: 'input[name="username"]',
    password: 'input[name="password"]',
    submit: 'button[type="submit"]',
    errorMessage: '.bg-error-container\\/30, .text-error',
  },
  register: {
    customerToggle: 'text=As Customer',
    vendorToggle: 'text=As Artisan/Vendor',
    firstName: 'input[name="first_name"]',
    lastName: 'input[name="last_name"]',
    username: 'input[name="username"]',
    email: 'input[name="email"]',
    phone: 'input[name="phone"]',
    password: 'input[name="password"]',
    confirmPassword: 'input[name="password2"]',
    shopName: 'input[name="shop_name"]',
    vendorType: 'select[name="vendor_type"]',
    location: 'input[name="location"]',
    submit: 'button[type="submit"]',
    successMessage: '.bg-green-100, .text-green-800',
  },
  nav: {
    exploreProducts: 'text=Explore Products',
    findAteliers: 'text=Find Ateliers',
    support: 'text=Support',
    cart: 'span.material-symbols-outlined:has-text("shopping_bag")',
    profileMenu: 'button:has(span.material-symbols-outlined:has-text("person")), button:has-text("priya"), button:has-text("admin"), button:has-text("raja_tailors")',
    adminDashboard: 'text=Admin Dashboard',
    vendorDashboard: 'text=Vendor Dashboard',
    logout: 'button:has-text("Logout"), button:has-text("Log Out"), span:has-text("Logout"), span:has-text("Log Out")',
  },
  products: {
    searchInput: 'input[placeholder*="Search"]',
    categorySelect: 'select',
    sortSelect: 'select',
    productCard: '.group.bg-surface-container-lowest',
    productTitle: 'h3',
    addToCart: 'button:has-text("Add to Bag"), button:has-text("Add to Cart")',
  },
  cart: {
    checkoutBtn: 'button:has-text("Proceed to Checkout"), button:has-text("Checkout")',
    name: 'input[name="shipping_name"]',
    address: 'textarea[name="shipping_address"], input[name="shipping_address"]',
    city: 'input[name="shipping_city"]',
    state: 'input[name="shipping_state"]',
    pincode: 'input[name="shipping_pincode"]',
    phone: 'input[name="shipping_phone"]',
    placeOrder: 'button[type="submit"]',
  },
  appointments: {
    typeSelect: 'select[name="appointment_type"]',
    dateInput: 'input[type="date"]',
    timeInput: 'select[name="time_slot"]',
    notes: 'textarea[name="notes"]',
    submit: 'button:has-text("Schedule Consultation")',
  },
  support: {
    subject: 'input[name="subject"]',
    issueType: 'select[name="issue_type"]',
    description: 'textarea[name="description"]',
    submit: 'button:has-text("Submit Inquiry")',
  },
  reviews: {
    rating: 'select[name="rating"]',
    title: 'input[name="title"]',
    comment: 'textarea[name="comment"]',
    submit: 'button:has-text("Submit Review")',
  },
  vendor: {
    sidebar: {
      products: 'text=My Products',
      addProduct: 'text=Add Product',
      appointments: 'text=Appointments',
      promotions: 'text=Promotions',
      profile: 'text=Edit Profile',
    },
    addProduct: {
      title: 'input[name="title"]',
      price: 'input[name="price"]',
      stock: 'input[name="stock"]',
      category: 'select[name="category"]',
      description: 'textarea[name="description"]',
      sku: 'input[name="sku"]',
      isCustomizable: 'input[name="is_customizable"]',
      submit: 'button[type="submit"]',
    },
  },
  admin: {
    sidebar: {
      verifications: 'text=Verifications',
      reviews: 'text=Reviews',
      ads: 'text=Advertisements, text=Ads',
      tickets: 'text=Support',
    },
  },
};
